# Generated by Django 2.2.7 on 2019-11-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20191112_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DurationField(),
        ),
    ]
